services:
  kotlinbot:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - OPENAI_KEY=${OPENAI_KEY}
    network_mode: host

  mongodb:
    image: arm64v8/mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    networks:
        - db_network

  postgres:
    build:
      context: .
      dockerfile: Dockerfile-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: images
    labels:
      - "org.springframework.boot.service-connection=postgres"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - db_network

networks:
  db_network:
    driver: bridge
